### ISSUE TITLE
"Error: Could not determine field type PARAM NAME in DTO" when field type is number

### ISSUE THREAD

**Issue by jordykoppen** [fjodor-rybakov/discord-nestjs#563]
Heya, when defining a field with type `number` as followed:
```typescript
export class RemoveDto {
  @Param({
    name: 'position',
    description: 'Position of song to remove from Queue',
    required: true,
  })
  position: number;
}
```

I receive this error:

```
Error: Could not determine field type position in class RemoveDto
    at OptionResolver.getApplicationOptionTypeByArg (/home/NAME/workspace/APP/node_modules/@discord-nestjs/core/src/resolvers/option/option.resolver.ts:117:15)
    at /home/NAME/workspace/APP/node_modules/@discord-nestjs/core/src/resolvers/option/option.resolver.ts:34:16
    at Array.map (<anonymous>)
    at OptionResolver.resolve (/home/NAME/workspace/APP/node_modules/@discord-nestjs/core/src/resolvers/option/option.resolver.ts:25:30)
    at BuildApplicationCommandService.resolveCommandOptions (/home/NAME/workspace/APP/node_modules/@discord-nestjs/core/src/services/build-application-command.service.ts:59:50)
    at CommandResolver.resolve (/home/NAME/workspace/APP/node_modules/@discord-nestjs/core/src/resolvers/command/command.resolver.ts:43:7)
    at /home/NAME/workspace/APP/node_modules/@discord-nestjs/core/src/services/discord-resolver.service.ts:71:9
    at async Promise.all (index 2)
    at DiscordResolverService.resolveDecorators (/home/NAME/workspace/APP/node_modules/@discord-nestjs/core/src/services/discord-resolver.service.ts:68:30)
    at DiscordResolverService.onModuleInit (/home/NAME/workspace/APP/node_modules/@discord-nestjs/core/src/services/discord-resolver.service.ts:55:5)
```

If i change it to `string` it works just fine.
I assume this is a bug but let me know if I'm doing something wrong.

Cheers!

**Comment by fjodor-rybakov** [comment]
Sorry, there is an mistake in the documentation. Only `string` and `boolean` are resolved automatically. In all other cases, you need to specify the type.
