### ISSUE TITLE
 "classGuards is not iterable" with globalGuards

### ISSUE THREAD

**Issue by celianvdb** [fjodor-rybakov/discord-nestjs#683]
Hello, I got a little issue while trying to use global guards. Thanks in advance !

**Describe the bug**
I can't register a global guard ( which work perfectly applied directly on my prefix command ) without getting this error.
``` bash

TypeError: classGuards is not iterable
    at GuardResolver.<anonymous> (/home/celian/pro/code/HIDDEN/HIDDEN/HIDDEN/node_modules/@discord-nestjs/core/src/resolvers/guard/guard.resolver.ts:75:10)
    at Generator.next (<anonymous>)
    at /home/celian/pro/code/HIDDEN/HIDDEN/HIDDEN/node_modules/@discord-nestjs/core/dist/resolvers/guard/guard.resolver.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/home/celian/pro/code/HIDDEN/HIDDEN/HIDDENnode_modules/@discord-nestjs/core/dist/resolvers/guard/guard.resolver.js:13:12)
    at GuardResolver.applyGuard (/home/celian/pro/code/HIDDEN/HIDDEN/HIDDENnode_modules/@discord-nestjs/core/dist/resolvers/guard/guard.resolver.js:89:16)
    at EventResolver.<anonymous> (/home/celian/pro/code/HIDDEN/HIDDEN/HIDDENnode_modules/@discord-nestjs/core/src/resolvers/event/event.resolver.ts:58:64)
    at Generator.next (<anonymous>)
    at fulfilled (/home/celian/pro/code/HIDDEN/HIDDEN/HIDDEN/node_modules/@discord-nestjs/core/dist/resolvers/event/event.resolver.js:14:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**

Here is my guard ( from example of this repo )

_MessageFromUser.guard.ts_
``` javascript
import { DiscordGuard } from '@discord-nestjs/core';
import { Message } from 'discord.js';

export class MessageFromUserGuard implements DiscordGuard {
  canActive(event: 'messageCreate', [message]: [Message]): boolean {
    return !message.author.bot;
  }
}
```

Here is my DiscordModule import from my app.module.ts
``` javascript
imports: [
  DiscordModule.forRootAsync({
    useFactory: () => ({
      token: config.discord.token,
      discordClientOptions: {
        intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES],
        shardCount: getDiscordShardTotal(),
        shards: getDiscordShardId(),
      },
      prefix: '!',
    }),
  }),
],
providers: [
    {
      provide: registerGuardGlobally(),
      useClass: MessageFromUserGuard,
    },
],
```

BUT if I apply the guard directly on the method like below, it works perfectly : 

``` javascript
@Injectable()
export class InvitCommand {
  constructor(private readonly guildMembersService: GuildMembersService) {}
  @PrefixCommand('invit')
  @UseGuards(MessageFromUserGuard, IsRegisteredGuildGuard)
  @UsePipes(PrefixCommandTransformPipe)
  async onInvitCommand({ author, guild }: Message) {
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const user = await this.guildMembersService.findOrCreate(
      author.id,
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
      guild!.id,
    );
    return user.inviteCode;
  }
}
```

**Additional context**
```
    "@discord-nestjs/common": "^3.0.1",
    "@discord-nestjs/core": "^3.0.1",
```

**Comment by fjodor-rybakov** [comment]
Thanks for report! Fixed in 3.0.2 version
