### ISSUE TITLE
Question : How to defer an interaction reply? (INTERACTION_ALREADY_REPLIED)

### ISSUE THREAD

**Issue by elAndyG** [fjodor-rybakov/discord-nestjs#774]
How would you do an interaction reply with a defer message? I tried accessing the actual executionContext, but cannot seem to get the PostInteractionCollector to execute either. Do you have an example with the `PlayCommand` using a defer reply with the interactions?

```javascript
@Command({
  name: 'play',
  description: 'Plays a song',
})
@UsePipes(TransformPipe)
@UseCollectors(PostInteractionCollector)
export class PlayCommand implements DiscordTransformedCommand<PlayDto> {
  async handler(@Payload() dto: PlayDto, executionContext: TransformedCommandExecutionContext): Promise<InteractionReplyOptions> {
    await executionContext.interaction.deferReply({ ephemeral: true });

    // *****************************
    // DO LONG PROCESS HERE
     await some.long_process_here();
    // ******************************
 
    const row = new MessageActionRow().addComponents(
      new MessageButton()
        .setCustomId('primary')
        .setLabel(dto.song)
        .setStyle('PRIMARY'),
    );

    return {
      content: 'Click on the button to play the song!',
      components: [row],
    };
  }
}
```

What i tried instead of the return
```javascript
      await executionContext.interaction.editReply({
            content: 'Click on the button to play the song!',
            components: [row],
     });  // But then interactions do not work
```

Error:
```basg
/Users/ME/project/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:94
    if (this.deferred || this.replied) throw new Error('INTERACTION_ALREADY_REPLIED');
                                             ^
Error [INTERACTION_ALREADY_REPLIED]: The reply to this interaction has already been sent or deferred.
    at CommandInteraction.reply (/Users/ME/project/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:94:46)
    at CommandExplorer.<anonymous> (/Users/ME/project/node_modules/@discord-nestjs/core/src/explorers/command/command.explorer.ts:135:46)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ME/projectt/node_modules/@discord-nestjs/core/dist/explorers/command/command.explorer.js:14:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Desktop (please complete the following information):**

- OS:Mac

**Comment by DezziCool** [comment]
hi @elAndyG 
here is my example
![image](https://user-images.githubusercontent.com/51258699/175832320-68e6b75c-2453-4d55-9989-cf2191783068.png)

**Comment by elAndyG** [comment]
Hi @DezziCool . That is the winner!!! Thank you so much for the follow up.... (literally lol)

closing ticket. great sggestion above.
