### ISSUE TITLE
Reopen Impossible to use with nestjs-telegraf

### ISSUE THREAD

**Issue by Simkav** [fjodor-rybakov/discord-nestjs#841]
**Describe the bug**
Usage discord-nestjs with nestjs-telegraf will throw error

**Dependencies**
@discord-nestjs/core": "^4.2.0"
discord.js": "^14.2.0"
telegraf": "^4.8.6"
nestjs-telegraf": "^2.6.0"

**To Reproduce**
1. Register TelegrafModule with options in app module
2. Register DiscordModule with options in app module
3. Register any discord handler decorator like @Once('ready')

**Expected behavior**
I expect it to work

**Desktop**
- OS: Ubuntu
- Version 22.04
- Node: 16.15.0

**Additional context**
Stacktrace:
> TypeError: Cannot read properties of undefined (reading 'allowEvents')
    at /home/simkav/Projects/testnest/node_modules/@discord-nestjs/core/src/explorers/middleware/middleware.explorer.ts:32:25
    at Array.filter (<anonymous>)
    at MiddlewareExplorer.<anonymous> (/home/simkav/Projects/testnest/node_modules/@discord-nestjs/core/src/explorers/middleware/middleware.explorer.ts:29:52)
    at Generator.next (<anonymous>)
    at /home/simkav/Projects/testnest/node_modules/@discord-nestjs/core/dist/explorers/middleware/middleware.explorer.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/home/simkav/Projects/testnest/node_modules/@discord-nestjs/core/dist/explorers/middleware/middleware.explorer.js:13:12)
    at MiddlewareExplorer.applyMiddleware (/home/simkav/Projects/testnest/node_modules/@discord-nestjs/core/dist/explorers/middleware/middleware.explorer.js:47:16)
    at EventExplorer.<anonymous> (/home/simkav/Projects/testnest/node_modules/@discord-nestjs/core/src/explorers/event/event.explorer.ts:64:43)
    at Generator.next (<anonymous>)

**Comment by Simkav** [comment]
Patched version 4.2.0 still not workin
Added minimal [repository](https://github.com/Simkav/discordwithtelegraf) with reproducing
Just update .env file with

> 
TG_TOKEN=5718810852:AAE6QIBfQ7lpmYPXXLdMLnf6l_4on81_x28
DS_TOKEN=MTAwODY4NTE3NTMyMTkyMzY0NA.GMAd3g.dCd9YdzgTJ1RtFPpg-sU96qVVPsVoe1JwSdlDw

**Comment by fjodor-rybakov** [comment]
Thanks! Should fixed in 4.2.1 version
