### ISSUE TITLE
Documentation: Example for exception middleware

### ISSUE THREAD

**Issue by manuel-rw** [fjodor-rybakov/discord-nestjs#940]
Hello everyone,

thank you for this amazing package.
I was wondering, if there is a possibility to use the middleware to catch any exceptions happening during command interactions.

**Current behavior**:
If an exception occurs during a command, the entire application will crash:

```
    throw new Error("a very bad exception");
          ^
Error: a very bad exception
    at StatusCommand.handler (<censored>.command.ts:48:11)
    at CommandExplorer.<anonymous> (<censored>\node_modules\@discord-nestjs\core\src\explorers\command\command.explorer.ts:153:64)
    at Generator.next (<anonymous>)
    at fulfilled (<censored>\node_modules\@discord-nestjs\core\dist\explorers\command\command.explorer.js:14:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

In Discord, the interaction will time out:

![image](https://user-images.githubusercontent.com/30572287/208265700-9cd52e14-f863-468b-881e-5ac7caaa93b9.png)

All interaction commands now seem to be broken and do not respond.

**Desired behavior**:

I would like to be able to catch exceptions during commands and respond with an embed featuring the exception message and type.
The current middleware example does not seem to mention such use cases and I wasn't able to figure it out myself:
https://www.npmjs.com/package/@discord-nestjs/core#user-content-%E2%84%B9%EF%B8%8F-middleware-

**Comment by manuel-rw** [comment]
Never mind, I just noticed that they are called exception filters. Sorry for the trouble! 😂
