### ISSUE TITLE
Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by fishuke** [fjodor-rybakov/discord-nestjs#948]
```
TypeError: Cannot read properties of undefined (reading 'map')
    at RegisterCommandService.<anonymous> (/usr/src/app/node_modules/@discord-nestjs/core/dist/services/register-command.service.js:73:54)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@discord-nestjs/core/dist/services/register-command.service.js:17:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by fishuke** [comment]
If you assign registerCommandOptions to undefined, this happens. Easily fixable.
