### ISSUE TITLE
Modal example does not work correctly

### ISSUE THREAD

**Issue by marcin-stasiak** [fjodor-rybakov/discord-nestjs#979]
**Describe the bug**
Modal example does not work correctly

```
[Nest] 88356  - 05.02.2023, 14:43:31   ERROR [ExceptionsHandler] Cannot destructure property 'username' of 'undefined' as it is undefined.
TypeError: Cannot destructure property 'username' of 'undefined' as it is undefined.
    at RegisterCommand.onModuleSubmit (/src/discord/commands/register.command.ts:61:37)
    at /node_modules/@nestjs/core/helpers/external-context-creator.js:70:33
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at target (/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)
    at /node_modules/@nestjs/core/helpers/external-proxy.js:9:24
```

**To Reproduce**

1. Just send modal.

**Comment by fjodor-rybakov** [comment]
Thanks! Fixed in next version
